### PR TITLE
[ Refactor ]  Make this project more engineering

### PR DESCRIPTION
**Pull request by TechQuery**
Split **Core Classes** (`Puppeteer`, `Browser` & `Page`) into **Independent Source-code Files**, and add **Engineering Configuration** & **API documentation** files.

### CODE REVIEW

**Comment by autonome** [comment]
This is fantastic, thanks so much! You have vastly improved my original code. I'm going to merge this now.

However, before releasing new version on NPM I do want to write a test, and ensure it works against my existing scripts. If there are issues, we can fix here in the new code.

**Comment by TechQuery** [comment]
Oh, thanks so much! And https://github.com/TechQuery/Puppeteer-IE/tree/master/test may be help

**Comment by autonome** [comment]
👍🏼👍🏼👍🏼 Thanks, I'll start with that!

**Comment by TechQuery** [comment]
You can host `/docs` folder by **GitHub Pages** to show **JS API document** online.

**Pull request merged**
